import React, { useState } from 'react';
import Header from './Header';
import PrivacyNotice from './PrivacyNotice';
import { ToastNotification } from './SkeletonLoader';
import { translations } from '../utils/translations';
import { Download, CheckCircle2, ShieldCheck, User, Calendar, Clock, FileText, ArrowLeft, Home, PhoneCall, Stethoscope } from 'lucide-react';

export default function PrescriptionScreen({
  user,
  consultation,
  lang = 'en',
  onLangChange,
  onBack,
  onNext
}) {
  const t = translations[lang] || translations.en;
  const [downloading, setDownloading] = useState(false);
  const [toastMessage, setToastMessage] = useState(null);

  // Dynamic Medicine List (handles 1 to 10+ items cleanly)
  const medicines = consultation?.medicines && consultation.medicines.length > 0
    ? consultation.medicines
    : [
        { name: "Paracetamol (Crocin)", strength: "500 mg", dose: "1 Tablet", duration: "5 Days", instructions: "Twice daily after meal" },
        { name: "Amoxicillin", strength: "250 mg", dose: "1 Capsule", duration: "7 Days", instructions: "Every 8 hours with water" },
        { name: "Vitamin C & Zinc", strength: "500 mg", dose: "1 Chewable", duration: "10 Days", instructions: "Once daily morning" },
        { name: "ORS Hydration Sachet", strength: "21.8 g", dose: "1 Sachet in 1L", duration: "As needed", instructions: "Sip throughout day" }
      ];

  const doctorName = consultation?.ashaWorkerAssigned?.fullName || "Dr. Sanjeevani Specialist";
  const doctorReg = "MCI-2024-884920";
  const patientIdFormatted = user?._id ? `PAT-${user._id.slice(-6).toUpperCase()}` : 'PAT-804921';
  const currentDate = new Date().toLocaleDateString(lang === 'hi' ? 'hi-IN' : 'en-US', {
    dateStyle: 'medium'
  });

  const handleDownloadPDF = () => {
    setDownloading(true);
    setToastMessage("Preparing official digital prescription PDF...");
    setTimeout(() => {
      window.print();
      setDownloading(false);
      setToastMessage("Prescription saved successfully!");
      setTimeout(() => setToastMessage(null), 3000);
    }, 400);
  };

  const speechText = `Prescription generated by ${doctorName} for ${user?.fullName || 'Patient'}. Prescribed medicines include ${medicines.map(m => m.name).join(', ')}. Please follow dosage instructions carefully.`;

  return (
    <div className="screen-container prescription-page">
      <Header
        currentLang={lang}
        onLangChange={onLangChange}
        textToSpeak={speechText}
        speechLabel={t.listen}
      />

      <main className="main-content">
        <div className="card-wrapper printable-prescription animate-fade-in">
          {/* Top Prescription Banner */}
          <div className="prescription-header">
            <div className="rx-badge-group">
              <span className="rx-symbol">Rx</span>
              <div className="rx-titles">
                <h2>{t.prescriptionTitle}</h2>
                <p className="rx-subtitle">{t.generatedByDoctor}</p>
              </div>
            </div>
            <div className="verified-sign-badge signature-badge-shine">
              <CheckCircle2 size={18} className="sign-icon" />
              <span>{t.digitallyVerified}</span>
            </div>
          </div>

          {/* Patient Info Bar */}
          <div className="info-strip rx-patient-strip">
            <div className="info-item">
              <span className="info-label">Patient Name</span>
              <span className="info-value highlight">{user?.fullName || 'Sanjeevani Patient'}</span>
            </div>
            <div className="info-item">
              <span className="info-label">{t.patientId}</span>
              <span className="info-value">{patientIdFormatted}</span>
            </div>
              <div className="info-item">
              <span className="info-label">{t.dateTime}</span>
              <span className="info-value">{currentDate}</span>
            </div>
            <div className="info-item">
              <span className="info-label">Village Code</span>
              <span className="info-value">{user?.villageCode || 'VIL-102'}</span>
            </div>
          </div>

          {/* Attending Doctor Profile Block */}
          <div className="doctor-profile-card">
            <div className="doc-avatar-large">
              <Stethoscope size={28} />
            </div>
            <div className="doc-details-group">
              <h3 className="doc-name">{doctorName}</h3>
              <p className="doc-qualifications">MBBS, MD (General Medicine) • Tele-Health Consultant</p>
              <p className="doc-reg-no">Medical Council Reg No: <strong>{doctorReg}</strong></p>
            </div>
            <div className="doc-signature-badge signature-badge-shine">
              <span className="sig-text">Digitally Signed</span>
              <span className="sig-date">{currentDate}</span>
            </div>
          </div>

          {/* Dynamic Medicines Table */}
          <div className="medicines-section">
            <h4 className="section-title">
              <FileText size={18} />
              <span>{t.medicinesHeader}</span>
            </h4>

            <div className="table-responsive">
              <table className="rx-table">
                <thead>
                  <tr>
                    <th>#</th>
                    <th>{t.medicineName}</th>
                    <th>{t.strength}</th>
                    <th>{t.dosage}</th>
                    <th>{t.duration}</th>
                    <th>{t.instructions}</th>
                  </tr>
                </thead>
                <tbody>
                  {medicines.map((item, idx) => (
                    <tr key={idx}>
                      <td className="row-num">{idx + 1}</td>
                      <td className="med-name"><strong>{item.name}</strong></td>
                      <td>{item.strength}</td>
                      <td>{item.dose}</td>
                      <td>{item.duration}</td>
                      <td className="med-instructions">{item.instructions}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>

          {/* Advice & Follow-Up Panels Grid */}
          <div className="rx-panels-grid">
            {/* Advice Panel */}
            <div className="rx-panel advice-panel">
              <h4>{t.doctorAdvice}</h4>
              <ul className="advice-bullets">
                <li>Drink plenty of boiled or warm water throughout the day.</li>
                <li>Take adequate rest and avoid heavy physical labor for 3 days.</li>
                <li>Complete the full course of prescribed antibiotics.</li>
              </ul>
            </div>

            {/* Follow-up Panel */}
            <div className="rx-panel follow-up-panel">
              <h4>{t.followUpTitle}</h4>
              <p className="follow-up-date">
                Recommended Review Date: <strong>7 Days from today</strong>
              </p>
              <p className="emergency-note">
                ⚠ If high fever persists (&gt;102°F) or breathing difficulty develops, visit the nearest Primary Health Center immediately.
              </p>
            </div>
          </div>

          {/* Important Banner with Download CTA */}
          <div className="download-banner">
            <div className="banner-left">
              <ShieldCheck size={24} className="banner-icon" />
              <div>
                <p className="banner-title">Official Sanjeevani Medical Document</p>
                <p className="banner-sub">Accepted at all empaneled government clinics & ASHA kiosks.</p>
              </div>
            </div>
            <button className="btn-primary sm" onClick={handleDownloadPDF} disabled={downloading}>
              <Download size={18} />
              <span>{downloading ? 'Preparing PDF...' : t.downloadSave}</span>
            </button>
          </div>

          {/* Bottom Navigation Actions */}
          <div className="screen-actions flex-between no-print">
            <button className="btn-secondary" onClick={onBack}>
              <ArrowLeft size={18} />
              <span>{t.goBack}</span>
            </button>

            <button className="btn-primary" onClick={onNext}>
              <span>{t.returnHome}</span>
              <Home size={18} />
            </button>
          </div>
        </div>

        {toastMessage && (
          <ToastNotification
            message={toastMessage}
            type="success"
            onClose={() => setToastMessage(null)}
          />
        )}

        <PrivacyNotice lang={lang} />
      </main>
    </div>
  );
}
